# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Pass - Sponsorship(ccf64fef-5be7-4734-bfea-744554fdade5)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -l $(LOCATION) -n fabmedical-$(SUFFIX)2'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/Hands-on lab/arm/'
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
